services:
  db:
    image: mariadb:latest
    container_name: iot_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=home_automation
      - MARIADB_USER=home_automation_user
      - MARIADB_PASSWORD=0BXY5[ei<*6__nG(}BR
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: iot_home_automation_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Transmitem Spring Boot-ului parametrii DB prin variabile de mediu,
      # (sau direct in application.properties)
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/home_automation
      SPRING_DATASOURCE_USERNAME: home_automation_user
      SPRING_DATASOURCE_PASSWORD: 0BXY5[ei<*6__nG(}BR

volumes:
  mariadb_data:
